Data format for visualization send to google api
BuildForSDG/Team-102-GoodHealthAndWellBeing pull request #10
Opened 2020-05-10 11:34 UTC by blackalbino01

## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-10 12:54 UTC, AnthoniaOkafor approved these changes
Okay

2020-05-14 01:59 UTC, AnthoniaOkafor requested changes
Please don't use your master branch. Open a feature branch

2020-05-19 22:48 UTC, happyjosh-tech approved these changes

2020-05-19 22:49 UTC, merged

2020-05-20 00:55 UTC, AnthoniaOkafor commented
Hello @happyjosh-tech  and @blackalbino01, I couldn't change my first review for this PR but I later requested for a change asking for a feature branch to be used instead of the master branch. Also I can't see file changes in this PR that addressed issue #10 that was closed.